### ISSUE TITLE
MAC Address IoT:bit

### ISSUE THREAD

**Issue by diegomore** [elecfreaks/learn-en#2]
Good morning. I am writing to you from Malaga (Spain). I am using the IoT:bit expansion card with micro:bit and I need to know the MAC address to be able to connect to my institute's Wi-Fi network. How would I know the MAC address of this board? Thank you so much.

dmorrom@gmail.com

**Comment by elecfreaks1** [comment]
If you need to find the MAC address of your IoT:bit, one efficient method is to set up a mobile hotspot from your phone and connect the IoT:bit to this hotspot. Once connected, you can check the list of connected devices on your phone's settings to find the MAC address of the IoT:bit. I believe this is one of the quickest ways to obtain the device's MAC address.
